services:
  postgres_db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple-go-rest
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - go-network

  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple-go-rest
      - DB_PORT=5432
    depends_on:
      - postgres_db
    networks:
      - go-network

networks:
  go-network:

volumes:
  db-data: